site_name: Diplomarbeit von Simon Dückert
site_url: https://simondueckert.github.io/diploma-thesis/de/
docs_dir: src
site_dir: ../docs/de
edit_uri: ''

nav:
    - Kurzfassung: index.md
    - Vorwort: 2-0-preface.md
    - Einführung: 3-0-introduction.md
    - Vorüberlegungen: 4-0-considerations.md
    - Konzeption: 5-0-conception.md
    - Verifikation: 6-0-verification.md
    - Ausblick: 7-0-outlook.md
    - Glossar: 8-0-glossary.md
    - Literaturverzeichnis: 9-0-bibliography-web.md
    - Download:
      - PDF-Version: https://github.com/simondueckert/diploma-thesis/blob/main/de/2000-Diplomarbeit-simondueckert-de.pdf
      - Word: https://github.com/simondueckert/diploma-thesis/blob/main/de/2000-Diplomarbeit-simondueckert-de.docx
      - HTML: https://github.com/simondueckert/diploma-thesis/blob/main/de/2000-Diplomarbeit-simondueckert-de.html
      - E-Book (epub): https://github.com/simondueckert/diploma-thesis/blob/main/de/2000-Diplomarbeit-simondueckert-de.epub
    - Links:
      - Webseite Simon: https://blog.dueckert.eu

theme:
    name: 'material'
    language: de
    palette:
      primary: yellow
    icon:
      logo: material/home
      repo: fontawesome/brands/github
    features:
      - toc.integrate
      - search.share

repo_name: 'simondueckert/diploma-thesis'
repo_url: 'https://github.com/simondueckert/diploma-thesis'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@simondueckert'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/in/simondueckert/'
        - icon: fontawesome/brands/github
          link: 'https://github.com/simondueckert'
    generator: false

plugins:
  - search
  - bibtex:
      bib_file: "DiplomarbeitSD.bib"
markdown_extensions:
  - footnotes