site_name: Diplomarbeit von Simon Dückert
site_url: https://simondueckert.github.io/diploma-thesis/de/
docs_dir: src
site_dir: ../docs/de
edit_uri: ''

nav:
    - Startseite: index.md
    - Vorwort: 2-0-preface.md
    - Einleitung: 3-0-introduction.md
    - Vorüberlegungen:
      - Rahmenbedingungen am IIS: 4-1-frameset-iis.md
      - Wissensformen: 4-2-forms-of-knowledge.md
      - Wissenstransportkanäle: 4-3-knowledge-transfer.md
    - Konzeption:
      - Anforderungen an ein Wissensmanagementsystem: 5-1-requirements.md
      - Methoden: 5-2-methods.md
      - Systemauswahl: 5-3-system-selection.md
      - Entscheidung: 5-4-decision.md
      - systemX I: 5-5-system-x-1.md
      - systemX II: 5-6-system-x-2.md
    - Verifikation: 6-0-verification.md
    - Ausblick: 7-0-outlook.md
    - Glossar: 8-0-glossary.md
    - Literaturverzeichnis: 9-0-bibliography-web.md
    - Download:
      - PDF-Version: https://github.com/simondueckert/diploma-thesis/blob/main/de/2000-Diplomarbeit-simondueckert-de.pdf
      - Word: https://github.com/simondueckert/diploma-thesis/blob/main/de/2000-Diplomarbeit-simondueckert-de.docx
      - HTML: https://github.com/simondueckert/diploma-thesis/blob/main/de/2000-Diplomarbeit-simondueckert-de.html
      - E-Book (epub): https://github.com/simondueckert/diploma-thesis/blob/main/de/2000-Diplomarbeit-simondueckert-de.epub
    - Links:
      - Webseite Simon: https://blog.dueckert.eu

theme:
    name: 'material'
    custom_dir: src/overrides
    language: de
    palette:
      primary: yellow
    icon:
      logo: material/home
      repo: fontawesome/brands/github
    features:
      - toc.integrate
      - search.share

repo_name: 'simondueckert/diploma-thesis'
repo_url: 'https://github.com/simondueckert/diploma-thesis'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@simondueckert'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/in/simondueckert/'
        - icon: fontawesome/brands/github
          link: 'https://github.com/simondueckert'
    giscus: true
    analytics:
        provider: custom
    generator: false

plugins:
  - search
  - bibtex:
      bib_file: "DiplomarbeitSD.bib"
markdown_extensions:
  - footnotes